version: "3"
services:
  myredis:
    image: redis:alpine
  gdanmaku:
    build: .
    image: gdanmaku-server:current
    volumes:
      - ./settings_local.py:/app/gdanmaku/settings_local.py
    ports:
      - "6080:80"
